[2024-01-07T13:54:18.743+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T13:54:18.763+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T13:54:18.763+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:54:18.807+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T13:54:18.828+0000] {standard_task_runner.py:57} INFO - Started process 1031 to run task
[2024-01-07T13:54:18.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpd4hgmiz1']
[2024-01-07T13:54:18.843+0000] {standard_task_runner.py:85} INFO - Job 253: Subtask copy_country_Postgres_To_GCS
[2024-01-07T13:54:18.973+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:54:19.190+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T13:54:19.208+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:19.225+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:19.252+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:54:19.258+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:54:19.258+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:54:19.275+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T135418, end_date=20240107T135419
[2024-01-07T13:54:19.330+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:54:19.366+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:53:02.628+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T15:53:02.653+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T15:53:02.653+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:53:02.687+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T15:53:02.695+0000] {standard_task_runner.py:57} INFO - Started process 4270 to run task
[2024-01-07T15:53:02.698+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp1n6fb7mz']
[2024-01-07T15:53:02.701+0000] {standard_task_runner.py:85} INFO - Job 357: Subtask copy_country_Postgres_To_GCS
[2024-01-07T15:53:02.792+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:53:03.008+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T15:53:03.026+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:03.041+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:03.064+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:53:03.070+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:53:03.071+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:53:03.088+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T155302, end_date=20240107T155303
[2024-01-07T15:53:03.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:53:03.179+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T16:06:01.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T16:06:01.896+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T16:06:01.896+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T16:06:01.917+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T16:06:01.926+0000] {standard_task_runner.py:57} INFO - Started process 4666 to run task
[2024-01-07T16:06:01.937+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpohlafgwq']
[2024-01-07T16:06:01.940+0000] {standard_task_runner.py:85} INFO - Job 376: Subtask copy_country_Postgres_To_GCS
[2024-01-07T16:06:02.035+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T16:06:02.180+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T16:06:02.197+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:06:02.212+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:06:02.240+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T16:06:02.249+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T16:06:02.250+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T16:06:02.268+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T160601, end_date=20240107T160602
[2024-01-07T16:06:02.318+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T16:06:02.352+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T17:53:22.701+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T17:53:22.729+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T17:53:22.729+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T17:53:22.761+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T17:53:22.768+0000] {standard_task_runner.py:57} INFO - Started process 7268 to run task
[2024-01-07T17:53:22.772+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmptkf2lupl']
[2024-01-07T17:53:22.775+0000] {standard_task_runner.py:85} INFO - Job 387: Subtask copy_country_Postgres_To_GCS
[2024-01-07T17:53:22.847+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T17:53:23.064+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T17:53:23.078+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:23.091+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:23.110+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T17:53:23.116+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T17:53:23.117+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T17:53:23.132+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T175322, end_date=20240107T175323
[2024-01-07T17:53:23.185+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T17:53:23.207+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T18:01:42.668+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T18:01:42.690+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T18:01:42.690+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T18:01:42.714+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T18:01:42.722+0000] {standard_task_runner.py:57} INFO - Started process 7515 to run task
[2024-01-07T18:01:42.727+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpbqs783fs']
[2024-01-07T18:01:42.730+0000] {standard_task_runner.py:85} INFO - Job 401: Subtask copy_country_Postgres_To_GCS
[2024-01-07T18:01:42.822+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T18:01:42.952+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T18:01:42.966+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:42.978+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:42.997+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T18:01:43.004+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T18:01:43.005+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T18:01:43.019+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T180142, end_date=20240107T180143
[2024-01-07T18:01:43.061+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T18:01:43.083+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:12:44.349+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:12:44.367+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:12:44.367+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:12:44.387+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T19:12:44.395+0000] {standard_task_runner.py:57} INFO - Started process 9397 to run task
[2024-01-07T19:12:44.398+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp3zyhvv63']
[2024-01-07T19:12:44.401+0000] {standard_task_runner.py:85} INFO - Job 418: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:12:44.467+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:12:44.591+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T19:12:44.606+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:44.617+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:44.636+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:12:44.642+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:12:44.643+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:12:44.658+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T191244, end_date=20240107T191244
[2024-01-07T19:12:44.690+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:12:44.713+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:13:57.971+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:13:58.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:13:58.004+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:13:58.033+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T19:13:58.041+0000] {standard_task_runner.py:57} INFO - Started process 9453 to run task
[2024-01-07T19:13:58.045+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmph_8t7fco']
[2024-01-07T19:13:58.049+0000] {standard_task_runner.py:85} INFO - Job 425: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:13:58.132+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:13:58.277+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T19:13:58.297+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:58.315+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:58.338+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:13:58.344+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:13:58.345+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:13:58.363+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T191357, end_date=20240107T191358
[2024-01-07T19:13:58.417+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:13:58.440+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:30:48.880+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:30:49.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:30:49.019+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:30:49.134+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T19:30:49.145+0000] {standard_task_runner.py:57} INFO - Started process 9959 to run task
[2024-01-07T19:30:49.149+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpgz_qayeu']
[2024-01-07T19:30:49.154+0000] {standard_task_runner.py:85} INFO - Job 443: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:30:49.264+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:30:49.422+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T19:30:49.443+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:49.458+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:49.490+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:30:49.500+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:30:49.500+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:30:49.519+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T193049, end_date=20240107T193049
[2024-01-07T19:30:49.562+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:30:49.587+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:59:16.625+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:59:16.662+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T19:59:16.662+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:59:16.692+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T19:59:16.700+0000] {standard_task_runner.py:57} INFO - Started process 10720 to run task
[2024-01-07T19:59:16.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmplnuyobh7']
[2024-01-07T19:59:16.711+0000] {standard_task_runner.py:85} INFO - Job 465: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:59:16.805+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:59:16.961+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T19:59:16.980+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:59:16.995+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:59:17.019+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:59:17.031+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:59:17.031+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:59:17.050+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T195916, end_date=20240107T195917
[2024-01-07T19:59:17.120+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:59:17.152+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T20:18:56.670+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T20:18:56.707+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T20:18:56.707+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T20:18:56.740+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T20:18:56.752+0000] {standard_task_runner.py:57} INFO - Started process 11243 to run task
[2024-01-07T20:18:56.757+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmph6iedhuw']
[2024-01-07T20:18:56.760+0000] {standard_task_runner.py:85} INFO - Job 475: Subtask copy_country_Postgres_To_GCS
[2024-01-07T20:18:56.861+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T20:18:57.018+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T20:18:57.039+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:57.053+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:57.076+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T20:18:57.085+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T20:18:57.104+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T201856, end_date=20240107T201857
[2024-01-07T20:18:57.170+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T20:18:57.201+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:09:05.760+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T21:09:05.814+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-01-07T21:09:05.814+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:09:05.913+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-06 00:00:00+00:00
[2024-01-07T21:09:05.932+0000] {standard_task_runner.py:57} INFO - Started process 12576 to run task
[2024-01-07T21:09:05.941+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmprmutxsae']
[2024-01-07T21:09:05.953+0000] {standard_task_runner.py:85} INFO - Job 499: Subtask copy_country_Postgres_To_GCS
[2024-01-07T21:09:06.159+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-06T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T21:09:06.636+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-01-07T21:09:06.674+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:09:06.699+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:09:06.812+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:09:06.871+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:09:06.882+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:09:08.930+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet
[2024-01-07T21:09:08.954+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240106T000000, start_date=20240107T210905, end_date=20240107T210908
[2024-01-07T21:09:08.979+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:09:08.981+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:09:08.982+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:09:09.003+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:09:09.003+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:09:09.006+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:09:09.075+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 499 for task copy_country_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet; 12576)
[2024-01-07T21:09:09.119+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:09:09.151+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
