[2024-01-07T13:54:16.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:16.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:16.726+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:54:16.753+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T13:54:16.761+0000] {standard_task_runner.py:57} INFO - Started process 1025 to run task
[2024-01-07T13:54:16.766+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp2vfxfoky']
[2024-01-07T13:54:16.770+0000] {standard_task_runner.py:85} INFO - Job 251: Subtask copy_country_Postgres_To_GCS
[2024-01-07T13:54:16.849+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:54:17.008+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T13:54:17.024+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:17.039+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:17.063+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:54:17.070+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:54:17.071+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:54:17.089+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T135416, end_date=20240107T135417
[2024-01-07T13:54:17.141+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:54:17.172+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:52:57.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.511+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:52:57.538+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:52:57.548+0000] {standard_task_runner.py:57} INFO - Started process 4265 to run task
[2024-01-07T15:52:57.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpoiozy4sl']
[2024-01-07T15:52:57.560+0000] {standard_task_runner.py:85} INFO - Job 356: Subtask copy_country_Postgres_To_GCS
[2024-01-07T15:52:57.654+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:52:57.811+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:52:57.829+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.846+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.874+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:52:57.882+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:52:57.920+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T15:52:57.929+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T15:52:59.993+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-{ds_nodash}.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T15:53:00.020+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T15:53:00.111+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:00.132+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:53:00.133+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:53:00.162+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155257, end_date=20240107T155300
[2024-01-07T15:53:00.259+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:53:00.297+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:58:23.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.292+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.292+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:58:23.317+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:58:23.324+0000] {standard_task_runner.py:57} INFO - Started process 4432 to run task
[2024-01-07T15:58:23.329+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpxhkxmrud']
[2024-01-07T15:58:23.337+0000] {standard_task_runner.py:85} INFO - Job 364: Subtask copy_country_Postgres_To_GCS
[2024-01-07T15:58:23.426+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:58:23.591+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:58:23.610+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.628+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.653+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:58:23.658+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:58:23.683+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined
[2024-01-07T15:58:23.721+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155823, end_date=20240107T155823
[2024-01-07T15:58:23.742+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T15:58:23.742+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.742+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.756+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.757+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.758+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T15:58:23.915+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 364 for task copy_country_Postgres_To_GCS (name 'ds_nodash' is not defined; 4432)
[2024-01-07T15:58:23.941+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T15:58:23.981+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T16:05:56.777+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.821+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.821+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T16:05:56.953+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T16:05:56.962+0000] {standard_task_runner.py:57} INFO - Started process 4660 to run task
[2024-01-07T16:05:56.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpzdwm84bo']
[2024-01-07T16:05:56.974+0000] {standard_task_runner.py:85} INFO - Job 374: Subtask copy_country_Postgres_To_GCS
[2024-01-07T16:05:57.061+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T16:05:57.201+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T16:05:57.220+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.234+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.266+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T16:05:57.272+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T16:05:57.306+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T16:05:57.315+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T16:05:59.438+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T16:05:59.452+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T16:05:59.491+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:59.507+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T16:05:59.508+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T16:05:59.526+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T160556, end_date=20240107T160559
[2024-01-07T16:05:59.593+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T16:05:59.625+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
