[2024-01-07T13:54:14.065+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:14.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:14.081+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:54:14.118+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T13:54:14.129+0000] {standard_task_runner.py:57} INFO - Started process 1020 to run task
[2024-01-07T13:54:14.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp2yr5u8li']
[2024-01-07T13:54:14.136+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask copy_course_Postgres_To_GCS
[2024-01-07T13:54:14.225+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:54:14.383+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T13:54:14.402+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:14.416+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:14.437+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:54:14.444+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T13:54:14.445+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:54:14.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T135414, end_date=20240107T135414
[2024-01-07T13:54:14.506+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:54:14.535+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:52:57.485+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.502+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.502+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:52:57.527+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:52:57.535+0000] {standard_task_runner.py:57} INFO - Started process 4264 to run task
[2024-01-07T15:52:57.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp1s92w8tx']
[2024-01-07T15:52:57.549+0000] {standard_task_runner.py:85} INFO - Job 355: Subtask copy_course_Postgres_To_GCS
[2024-01-07T15:52:57.642+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:52:57.790+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:52:57.807+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.823+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.847+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:52:57.854+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:52:57.894+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T15:52:57.903+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T15:52:59.998+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-{ds_nodash}.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T15:53:00.017+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T15:53:00.105+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:00.129+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:53:00.130+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:53:00.161+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155257, end_date=20240107T155300
[2024-01-07T15:53:00.219+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:53:00.249+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:58:23.278+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.298+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.299+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:58:23.328+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:58:23.338+0000] {standard_task_runner.py:57} INFO - Started process 4433 to run task
[2024-01-07T15:58:23.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpx_7ywup0']
[2024-01-07T15:58:23.349+0000] {standard_task_runner.py:85} INFO - Job 365: Subtask copy_course_Postgres_To_GCS
[2024-01-07T15:58:23.443+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:58:23.601+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:58:23.621+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.637+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.661+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:58:23.671+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:58:23.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined
[2024-01-07T15:58:23.720+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155823, end_date=20240107T155823
[2024-01-07T15:58:23.741+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T15:58:23.742+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.742+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.756+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.756+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.757+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T15:58:23.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 365 for task copy_course_Postgres_To_GCS (name 'ds_nodash' is not defined; 4433)
[2024-01-07T15:58:23.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T15:58:23.944+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T16:05:56.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.795+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T16:05:56.858+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T16:05:56.865+0000] {standard_task_runner.py:57} INFO - Started process 4659 to run task
[2024-01-07T16:05:56.869+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpvhj24ns0']
[2024-01-07T16:05:56.875+0000] {standard_task_runner.py:85} INFO - Job 373: Subtask copy_course_Postgres_To_GCS
[2024-01-07T16:05:57.028+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T16:05:57.188+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T16:05:57.207+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.223+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.247+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T16:05:57.254+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T16:05:57.286+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T16:05:57.293+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T16:05:59.438+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T16:05:59.451+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T16:05:59.479+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:59.493+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T16:05:59.494+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T16:05:59.511+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T160556, end_date=20240107T160559
[2024-01-07T16:05:59.571+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T16:05:59.601+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
